if(TURBOJPEG_PREFER_STATIC_LIB)
    set(TURBOJPEG_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
    if(WIN32)
        set(CMAKE_FIND_LIBRARY_SUFFIXES .a .lib ${CMAKE_FIND_LIBRARY_SUFFIXES})
    else()
        set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
    endif()
endif()

if(UNIX)
    find_package(PkgConfig QUIET)
    pkg_check_modules(_TURBOJPEG QUIET libturbojpeg)
endif()

find_path(TURBOJPEG_INCLUDE_DIR
    NAMES turbojpeg.h
    HINTS ${_TURBOJPEG_INCLUDEDIR})

find_library(TURBOJPEG_LIBRARY
    NAMES turbojpeg turbojpeg-static
    HINTS ${_TURBOJPEG_LIBDIR})

set(TURBOJPEG_INCLUDE_DIRS ${TURBOJPEG_INCLUDE_DIR})
set(TURBOJPEG_LIBRARIES ${TURBOJPEG_LIBRARY})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(TURBOJPEG
    REQUIRED_VARS
        TURBOJPEG_LIBRARY
        TURBOJPEG_INCLUDE_DIR)

mark_as_advanced(TURBOJPEG_INCLUDE_DIR TURBOJPEG_LIBRARY)

if(TURBOJPEG_PREFER_STATIC_LIB)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${TURBOJPEG_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES})
    unset(TURBOJPEG_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES)
endif()
